apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heartbeat-state
  namespace: snat-test
  labels:
    app: snat-heartbeat-dashboard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
