apiVersion: v1
kind: Service
metadata:
  name: snat-heartbeat-dashboard
  namespace: snat-test
  labels:
    app: snat-heartbeat-dashboard
spec:
  selector:
    app: snat-heartbeat-dashboard
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
